"""create tickets table

Revision ID: ff61c2041388
Revises: 
Create Date: 2026-06-30 22:05:22.781825

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'ff61c2041388'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('urgency', sa.String(length=16), nullable=True),
    sa.Column('sentiment', sa.String(length=16), nullable=True),
    sa.Column('ai_draft_reply', sa.Text(), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('confidence_flag', sa.String(length=16), nullable=True),
    sa.Column('human_reviewed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('billing', 'technical', 'account', 'bug_report', 'feature_request', 'general')", name='ck_tickets_category'),
    sa.CheckConstraint("confidence_flag IN ('ok', 'low_confidence')", name='ck_tickets_confidence_flag'),
    sa.CheckConstraint("sentiment IN ('positive', 'neutral', 'negative')", name='ck_tickets_sentiment'),
    sa.CheckConstraint("urgency IN ('low', 'medium', 'high', 'critical')", name='ck_tickets_urgency'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_category'), 'tickets', ['category'], unique=False)
    op.create_index(op.f('ix_tickets_created_at'), 'tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_tickets_urgency'), 'tickets', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tickets_urgency'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_created_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_category'), table_name='tickets')
    op.drop_table('tickets')
    # ### end Alembic commands ###
